// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	users2 "github.com/miyayamamasaru/go-idp/pkg/application/usecase/users"
	"github.com/miyayamamasaru/go-idp/pkg/handler/oauth"
	users3 "github.com/miyayamamasaru/go-idp/pkg/handler/users"
	"github.com/miyayamamasaru/go-idp/pkg/repository/oauth_clients"
	"github.com/miyayamamasaru/go-idp/pkg/repository/users"
)

// Injectors from wire.go:

func InitializeHander() (*HandlerSet, error) {
	db, err := ProvideDB()
	if err != nil {
		return nil, err
	}
	bunDB := ProvideBunDB(db)
	usersRepositoryInterface := users.NewUsersRepository(bunDB)
	usersRegisterUsecase := users2.NewUsersRegisterUsecase(usersRepositoryInterface)
	usersRegisterHandlerInterface := users3.NewUsersRegisterHandler(usersRegisterUsecase)
	oauthClientRepositoryInterface := oauth_clients.NewOauthClientRepository(bunDB)
	authorizeHandlerInterface := oauth.NewAuthorizeHandler(oauthClientRepositoryInterface)
	mainHandlerSet := &HandlerSet{
		UsersRegisterHandler:  usersRegisterHandlerInterface,
		OauthAuthorizeHandler: authorizeHandlerInterface,
	}
	return mainHandlerSet, nil
}

// wire.go:

var SuperSet = wire.NewSet(
	ProvideDB,
	ProvideBunDB,
)

// repository
var repositorySet = wire.NewSet(users.NewUsersRepository, oauth_clients.NewOauthClientRepository)

// usecase
var usecaseSet = wire.NewSet(users2.NewUsersRegisterUsecase)

// handler
var handlerSet = wire.NewSet(users3.NewUsersRegisterHandler, oauth.NewAuthorizeHandler)

type HandlerSet struct {
	UsersRegisterHandler  users3.UsersRegisterHandlerInterface
	OauthAuthorizeHandler oauth.AuthorizeHandlerInterface
}
