// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"github.com/labstack/echo/v5"
	users_usecase "github.com/miyayamamasaru/go-idp/pkg/application/usecase/users"
	"github.com/miyayamamasaru/go-idp/pkg/repository/users"
)

func InitializeRouter() (*echo.Echo, error) {
	db, err := ProvideDB()
	if err != nil {
		return nil, err
	}
	usersRepository := users.NewUsersRepository(db)
	usersRegisterUsecase := users_usecase.NewUsersRegisterUsecase(usersRepository)
	echoEcho := NewRouter(usersRegisterUsecase)
	return echoEcho, nil
}
