// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	users2 "github.com/miyayamamasaru/go-idp/pkg/application/usecase/users"
	users3 "github.com/miyayamamasaru/go-idp/pkg/handler/users"
	"github.com/miyayamamasaru/go-idp/pkg/repository/users"
)

// Injectors from wire.go:

func InitializeHander() (*HandlerSet, error) {
	db, err := ProvideDB()
	if err != nil {
		return nil, err
	}
	usersRepositoryInterface := users.NewUsersRepository(db)
	usersRegisterUsecase := users2.NewUsersRegisterUsecase(usersRepositoryInterface)
	usersRegisterHandlerInterface := users3.NewUsersRegisterHandler(usersRegisterUsecase)
	mainHandlerSet := &HandlerSet{
		UsersRegisterHandler: usersRegisterHandlerInterface,
	}
	return mainHandlerSet, nil
}

// wire.go:

var SuperSet = wire.NewSet(
	ProvideDB, users.NewUsersRepository, users2.NewUsersRegisterUsecase,
)

// handler
var handlerSet = wire.NewSet(users3.NewUsersRegisterHandler)

type HandlerSet struct {
	UsersRegisterHandler users3.UsersRegisterHandlerInterface
}
